// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpaMenu.Infrastructure.Shared.Data.Context.AccessControl;

#nullable disable

namespace OpaMenu.Infrastructure.Shared.Migrations.AccessControl
{
    [DbContext(typeof(AccessControlDbContext))]
    partial class AccessControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.AccessGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("GroupTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_type_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupTypeId");

                    b.ToTable("access_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2987c0d9-519f-6245-c920-889f697a658c"),
                            Code = "GRP_SYS_ADMIN",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grupo de super administradores",
                            GroupTypeId = new Guid("4dcb20a2-b350-3384-25a1-27d98e79d6ac"),
                            IsActive = true,
                            Name = "System Admins",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aee4edda-f145-f4c7-7edb-20a33888df4b"),
                            Code = "GRP_TENANT_ADMIN",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grupo de administradores de tenant",
                            GroupTypeId = new Guid("921ceb40-24ff-ed9e-7e0e-bf33042e9272"),
                            IsActive = true,
                            Name = "Tenant Admins",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.AccountAccessGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("UserAccountId", "AccessGroupId")
                        .IsUnique();

                    b.ToTable("account_access_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1e8f88f-6526-5bf8-6a70-c5238f40dd92"),
                            AccessGroupId = new Guid("2987c0d9-519f-6245-c920-889f697a658c"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserAccountId = new Guid("6bc3c728-4ffa-67f6-2ed9-d4f18594f4c0")
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuxiliarSchema")
                        .HasColumnType("text")
                        .HasColumnName("auxiliar_schema");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("secret_key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("application", (string)null);
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.GroupTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("group_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dcb20a2-b350-3384-25a1-27d98e79d6ac"),
                            Code = "SYSTEM_ADMIN",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Equipe de analistas do sistema",
                            IsActive = true,
                            Name = "Administradores do Sistema",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("921ceb40-24ff-ed9e-7e0e-bf33042e9272"),
                            Code = "TENANT_ADMIN",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administradores dos estabelecimentos",
                            IsActive = true,
                            Name = "Administradores do Tenant",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.ModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Key");

                    b.ToTable("module", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("13482be3-f205-837c-cceb-e28f14015000"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Visão geral do sistema",
                            IsActive = true,
                            Key = "DASHBOARD",
                            Name = "Dashboard",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = new Guid("f30c45da-30a3-45cb-f932-88af5354e1e6"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de grupos de adicionais",
                            IsActive = true,
                            Key = "ADITIONAL_GROUP",
                            Name = "Grupos de Adicionais",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/addon-groups"
                        },
                        new
                        {
                            Id = new Guid("4822a024-3dd0-674d-638d-ddee1f7b1a2b"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de adicionais",
                            IsActive = true,
                            Key = "ADITIONAL",
                            Name = "Adicionais",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/addons"
                        },
                        new
                        {
                            Id = new Guid("6f331ece-a4ea-74f6-158b-c7a5be39cc41"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de produtos",
                            IsActive = true,
                            Key = "PRODUCT",
                            Name = "Produtos",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/products"
                        },
                        new
                        {
                            Id = new Guid("aa19bde8-48c1-7dd4-1f18-bd177952614d"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configurações do sistema/estabelecimento",
                            IsActive = true,
                            Key = "SETTINGS",
                            Name = "Configurações",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/settings"
                        },
                        new
                        {
                            Id = new Guid("d8265dac-ea6a-353a-5bd5-065d519df46b"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de categorias",
                            IsActive = true,
                            Key = "CATEGORY",
                            Name = "Categorias",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/categories"
                        },
                        new
                        {
                            Id = new Guid("9b464720-4a29-d649-f64a-7b8ebec95bcf"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de pedidos",
                            IsActive = true,
                            Key = "ORDER",
                            Name = "Pedidos",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/orders"
                        },
                        new
                        {
                            Id = new Guid("f415b1d6-6989-b41d-dcb8-4a0a824fc7f1"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de mesas",
                            IsActive = true,
                            Key = "TABLE",
                            Name = "Mesas",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/tables"
                        },
                        new
                        {
                            Id = new Guid("20bf5030-e615-8586-a0b1-c624ce259deb"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de clientes",
                            IsActive = true,
                            Key = "CUSTOMER",
                            Name = "Clientes",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/customers"
                        },
                        new
                        {
                            Id = new Guid("a7060970-7bc8-8e98-4566-e00676be1578"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de pagamentos",
                            IsActive = true,
                            Key = "PAYMENT",
                            Name = "Pagamentos",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/payments"
                        },
                        new
                        {
                            Id = new Guid("3ad894aa-3bdf-db04-9715-a1134c4c8825"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de cupons",
                            IsActive = true,
                            Key = "COUPON",
                            Name = "Cupons",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/coupons"
                        },
                        new
                        {
                            Id = new Guid("de03bd4d-f7e9-0b1b-f3a3-2b5ea9ee30b8"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Programa de fidelidade",
                            IsActive = true,
                            Key = "LOYALTY",
                            Name = "Fidelidade",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/loyalty"
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RoleAccessGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AccessGroupId", "RoleId")
                        .IsUnique();

                    b.ToTable("role_access_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0cb54ff-a183-7932-d250-f75da02e1c75"),
                            AccessGroupId = new Guid("2987c0d9-519f-6245-c920-889f697a658c"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dcececfe-1dc2-7d14-910b-408d435c5582"),
                            AccessGroupId = new Guid("aee4edda-f145-f4c7-7edb-20a33888df4b"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            Code = "SUPER_ADMIN",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acesso total ao sistema",
                            IsActive = true,
                            IsSystem = false,
                            Name = "Super Administrador",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrador do estabelecimento",
                            IsActive = true,
                            IsSystem = false,
                            Name = "Administrador",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Actions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("actions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_key");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ModuleKey");

                    b.ToTable("role_permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6109438b-666b-c9ec-b56d-b3826c27e0f7"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "DASHBOARD",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("621b724b-3f07-a045-902c-e3742108cd46"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "DASHBOARD",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0e6a4fe-ce63-744f-46f0-f043ffc9f52a"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "ADITIONAL_GROUP",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ae09b375-68a5-cf77-c7a9-8a797517f359"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "ADITIONAL_GROUP",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("96874e72-413b-1374-d3f9-65a348bc5f1c"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "ADITIONAL",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3a5beddc-59ef-836a-5b68-b118654c6cfe"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "ADITIONAL",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f42751c1-e9eb-37ca-e52d-9de6b1ec1595"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "PRODUCT",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a36cd1b-803d-1e1f-bd56-98b59b75a5de"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "PRODUCT",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b99574-afa9-e011-da32-a4b56a6e8aa3"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "SETTINGS",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4ca88129-5a57-5042-36ee-4821d5bdd77d"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "SETTINGS",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("95f0c29e-53f9-5810-0c06-be2f013ed4c0"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "CATEGORY",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("710cf9d8-d056-c475-f3fd-63ef9f64bf2b"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "CATEGORY",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2553895f-dca2-074e-70bd-91f176a9a95e"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "ORDER",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5238e92d-8af1-3a3e-7ada-e005537e89b0"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "ORDER",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3f442530-6a55-c4de-1f7c-d84ca02127b7"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "TABLE",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("296d5a1c-cfee-0528-923e-97665c86fff4"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "TABLE",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4d30ea3f-980a-5243-b88d-3ab629c248d4"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "CUSTOMER",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("48110f70-f135-7fb4-e381-bd1cadeaa493"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "CUSTOMER",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cd3226c5-c36a-b664-fe33-98299080ff6d"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "PAYMENT",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6454f469-be9d-6322-23cc-67d0c099bf33"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "PAYMENT",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7207671f-3e58-dec0-c03c-256591af4c2f"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "COUPON",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("792de7db-6f24-f089-86c7-bebcf98f0fbb"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "COUPON",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("95fa54d7-c059-2560-77ef-5580ce321834"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "LOYALTY",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("23656d51-12f7-68d9-7f6d-29e7cd61b1ef"),
                            Actions = new List<string> { "READ", "CREATE", "UPDATE", "DELETE" },
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModuleKey = "LOYALTY",
                            RoleId = new Guid("4534e34a-3a31-ef0c-2a17-b57ea1d45cb6"),
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.UserAccounts.UserAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expires_at");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_reset_token");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bc3c728-4ffa-67f6-2ed9-d4f18594f4c0"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@opamenu.com.br",
                            FirstName = "System",
                            IsEmailVerified = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$rR/VYsNgEYRwaJt/bMn2ieq.izZrI8dUMfd4yottdElTWQL/vh7eO",
                            RoleId = new Guid("724add9f-febd-c615-19db-8e526968da25"),
                            Status = "Ativo",
                            UpdatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.MultiTenant.Tenant.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AddressComplement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AddressCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("AddressNeighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AddressNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AddressState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AddressZipcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingComplement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("BillingNeighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BillingState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("BillingStreet")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BillingZipcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Document")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LegalRepresentativeCpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("LegalRepresentativeEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LegalRepresentativeName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LegalRepresentativePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Dictionary<string, object>>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("tenants", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.AccessGroupEntity", b =>
                {
                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.GroupTypeEntity", "GroupType")
                        .WithMany("AccessGroups")
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GroupType");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.AccountAccessGroupEntity", b =>
                {
                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.AccessGroupEntity", "AccessGroup")
                        .WithMany("AccountAccessGroups")
                        .HasForeignKey("AccessGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.UserAccounts.UserAccountEntity", "UserAccount")
                        .WithMany("AccountAccessGroups")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.ModuleEntity", b =>
                {
                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.ApplicationEntity", "Application")
                        .WithMany("Modules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RoleAccessGroupEntity", b =>
                {
                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.AccessGroupEntity", "AccessGroup")
                        .WithMany("RoleAccessGroups")
                        .HasForeignKey("AccessGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RoleEntity", "Role")
                        .WithMany("RoleAccessGroups")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RolePermissionEntity", b =>
                {
                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.UserAccounts.UserAccountEntity", b =>
                {
                    b.HasOne("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.AccessGroupEntity", b =>
                {
                    b.Navigation("AccountAccessGroups");

                    b.Navigation("RoleAccessGroups");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.ApplicationEntity", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.GroupTypeEntity", b =>
                {
                    b.Navigation("AccessGroups");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.RoleEntity", b =>
                {
                    b.Navigation("RoleAccessGroups");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OpaMenu.Infrastructure.Shared.Entities.AccessControl.UserAccounts.UserAccountEntity", b =>
                {
                    b.Navigation("AccountAccessGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
